### ISSUE TITLE
Ошибка парсинга ответа Selectel

### ISSUE THREAD

**Issue by AxelPAL** [easmith/selectel-storage-php-class#19]
Selectel стал отвечать заголовком в формате HTTP2, поэтому класс падает, т.к. не может распарсить заголовок правильно.
Я поправил это в своем форке, но там изменений очень много - поэтому не делаю PR.
https://github.com/AxelPAL/selectel-storage-php-class/blob/master/src/SCurl.php#L195 - вот тут есть фикс для этого.

**Comment by easmith** [comment]
Исправил этот участок

**Comment by AxelPAL** [comment]
Отлично! Нужно еще только выпустить новую версию с этим исправлением.

**Comment by easmith** [comment]
Сделано

https://github.com/easmith/selectel-storage-php-class/releases/tag/v1.0.3
