### ISSUE TITLE
Использование различных версий заголовков HTTP

### ISSUE THREAD

**Issue by AxelPAL** [easmith/selectel-storage-php-class#20]
Я обнаружил, что Selectel может отвечать одним из следующих статусов:
HTTP/2 204 
HTTP/1.1 204 No Content
При втором варианте текущая реализация парсинга ответа работать не будет.
Можно парсить это иначе: либо разбивать строку по пробелу, либо сделать как здесь: https://github.com/AxelPAL/selectel-storage-php-class/blob/master/src/SCurl.php#L195

**Comment by easmith** [comment]
Уже учтены оба варианта:
https://github.com/easmith/selectel-storage-php-class/blob/master/src/SCurl.php#L191

**Comment by AxelPAL** [comment]
Вижу, прекрасно! Спасибо.
